version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services: 
  
  dump1090exporter:
    container_name: dump1090exporter
    image: flightawareadsb/dump1090exporter:dev
    ports:
      - "9105:9105"
    restart: always
    stop_signal: SIGINT
    command: [
      "--resource-path=http://${HOST_IP:?IP_ADDRESS_UNSET_ERROR}:8080/data",
    ]

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    depends_on:
      - dump1090exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--web.listen-address=:9090"
    ]
    ports:
      - 9090:9090
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:8.4.3-armv7
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${DISABLE_LOGIN}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_DEFAULT_THEME=${GRAFANA_THEME}
      - GF_SERVER_GRAFANA_PORT=${GRAFANA_PORT}

  node-exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    command: [
      "--path.rootfs=/host",
      "--web.listen-address=:9100",
    ]
    ports:
        - 9100:9100
    volumes:
        - "/:/host:ro,rslave"
    restart: always

  piaware-exporter:
    container_name: piaware_exporter
    image: piaware_exporter:1.0
    ports:
        - 9101:9101
    restart: always
    command: [
      "--piaware_host",
      "${HOST_IP}"
    ]