global:
  scrape_interval:     10s
  evaluation_interval: 10s
  # scrape_timeout is set to the global default (10s).

# A scrape configuration specifying scrape jobs
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: dump1090
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ["dump1090exporter:9105"]

  - job_name: node_exporter
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: piaware_exporter
    static_configs:
      - targets: ["piaware_exporter:9101"]
